name: Build Home Directory
run-name: Building dotfiles
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: cachix/install-nix-action@v27
          with:
            nix_path: nixpkgs=channel:nixos-unstable
        - run: nix run nixpkgs#home-manager build --flake .#default

    
