name: Build Home Directory
run-name: Building dotfiles
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Create Nix configuration
        run: echo '{}' > modules/home-manager/packages.nix

      - name: Apply Home Manager configuration
        run: nix run nixpkgs#home-manager -- build --flake .#hugo
      
      - uses: actions/upload-artifact@v4
        with:
          name: Config files
          path: result/home-files/.config
          include-hidden-files: true
          if-no-files-found: error
