name: Build Home Directory
run-name: Building dotfiles
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: DeterminateSystems/nix-installer-action@main
        - run: nix run nixpkgs#home-manager build -- --flake .#hugo

    
